### ISSUE TITLE
2.0 ¬ Checklist

### ISSUE THREAD

**Issue by Iohan-Voigt** [Matrix-Developers/Locadora-de-Veiculos#10]
### Descrição:

Como funcionário da locadora, devo cadastrar/editar/excluir o item checklist na devolução do veículo, para verificar o estado do veículo na devolução, calcular danos e aplicar à devolução e já encaminhar para uma mecânica caso seja necessário.

### Critério de aceitação:

- Será cadastrado:
    - Conferência dos acessórios alugados junto ao carro e também as avarias e funcionamento do mesmo;
    - Quantidade e tipo de combustível na devolução;
    - Verificação de multa;
    - Taxa de limpeza do carro.

**Comment by pedro-ca** [comment]
Verificar se podemos colocar como Won't fix e fechar
