### ISSUE TITLE
2.0 ¬ Dashboard dos veículos

### ISSUE THREAD

**Issue by ViniJordao** [Matrix-Developers/Locadora-de-Veiculos#11]
### Descrição:

Como funcionário da locadora, gostaria de visualizar os carros disponíveis, ocupados, que estão em manutenção; as reservas para hoje e chegadas pendentes, para organizar futuras locações e saber rapidamente qual o paradeiro de cada carro.

### **Críterio de aceitação:**

* A visualização será realizada em 3 classes:
  * Alugados;
  * Disponíveis;
  * Indisponíveis

**Comment by pedro-ca** [comment]
Verificar se podemos fechar
