### ISSUE TITLE
2.0 ¬ Visualizar veículo

### ISSUE THREAD

**Issue by GustavoMariano** [Matrix-Developers/Locadora-de-Veiculos#52]
### Descrição: 
Como funcionário, gostaria de visualizar as informações e imagens dos carros, para que eu possa mostrar ao cliente.

### Critério de aceitação:

* Será visualizado:
  * Todos os dados do veiculo selecionado, porém sem o poder de editar;
  * Também deve visualizar as imagens desse veículo.

**Comment by pedro-ca** [comment]
Verificar se podemos fechar
